[phases.setup]
nixPkgs = ["ffmpeg", "python311", "python311Packages.pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 app:app"
